package wiki

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// OpenKB-style scaffold (age-port-openkb-into-agentops-go-5qw.1): port OpenKB's
// KB workspace layout + config/state into Go so `ao wiki init` / `ao wiki use`
// stand up a usable wiki without the OpenKB Python. The layout is a SELF-
// CONTAINED workspace rooted at an explicit path — it deliberately does NOT
// write into the repo's private `.agents/` corpus or the gold `.ao/wiki` view,
// so the raw/private and gold/public boundaries are preserved (bead risk note).

// ScaffoldConfigRelPath is the config/state file location relative to the
// workspace root. It records the active model/language/entity-types/thresholds
// so subsequent `ao wiki` commands resolve the workspace deterministically.
const ScaffoldConfigRelPath = "wiki/config.yaml"

// ScaffoldStateRelPath records which workspace `ao wiki use` selected, relative
// to the directory `use` is run from (repo-local pointer; never global state).
const ScaffoldStateRelPath = ".ao/wiki/active-workspace"

// ScaffoldLayout is the canonical OpenKB-style directory layout `init` creates.
// Order is stable so the scaffold is deterministic and testable.
var ScaffoldLayout = []string{
	"raw",
	"wiki/sources",
	"wiki/summaries",
	"wiki/concepts",
	"wiki/entities",
	"wiki/explorations",
	"wiki/reports",
	"output/skills",
	"output/decks",
}

// scaffoldSeedFiles are the seed markdown files `init` writes (path -> initial
// content). They are written only when absent so re-running init is idempotent.
func scaffoldSeedFiles(cfg ScaffoldConfig) map[string]string {
	return map[string]string{
		"wiki/index.md": "# Wiki Index\n\nGenerated by `ao wiki init`. Pages compiled from sources land here.\n",
		"wiki/log.md":   "# Wiki Log\n\nAppend-only record of wiki operations.\n",
		"wiki/AGENTS.md": "# Wiki AGENTS schema\n\n" +
			"This wiki was initialized for model `" + cfg.Model + "` (language: " + cfg.Language + ").\n\n" +
			"## Entity types\n\n" + entityTypesMarkdown(cfg.EntityTypes) + "\n",
	}
}

func entityTypesMarkdown(types []string) string {
	if len(types) == 0 {
		return "_(none configured)_"
	}
	var b strings.Builder
	for _, t := range types {
		fmt.Fprintf(&b, "- %s\n", t)
	}
	return b.String()
}

// ScaffoldThresholds are the OpenKB-style tuning knobs that map onto AgentOps
// wiki behavior. Kept as a typed struct (not a bare map) so the config schema is
// explicit and round-trips losslessly.
type ScaffoldThresholds struct {
	// SummaryMinChars is the minimum source length before a summary is compiled.
	SummaryMinChars int `yaml:"summary_min_chars"`
	// ConceptMinMentions is how many times an entity must appear to become a concept page.
	ConceptMinMentions int `yaml:"concept_min_mentions"`
}

// DefaultScaffoldThresholds returns OpenKB-equivalent defaults.
func DefaultScaffoldThresholds() ScaffoldThresholds {
	return ScaffoldThresholds{SummaryMinChars: 200, ConceptMinMentions: 3}
}

// ScaffoldConfig is the authored config/state for an OpenKB-style wiki workspace.
type ScaffoldConfig struct {
	Model       string             `yaml:"model"`
	Language    string             `yaml:"language"`
	EntityTypes []string           `yaml:"entity_types"`
	Thresholds  ScaffoldThresholds `yaml:"thresholds"`
}

// DefaultScaffoldConfig returns a config with OpenKB-equivalent defaults, with
// model/language overridden by the caller (empty values fall back to defaults).
func DefaultScaffoldConfig(model, language string) ScaffoldConfig {
	if strings.TrimSpace(language) == "" {
		language = "en"
	}
	return ScaffoldConfig{
		Model:       strings.TrimSpace(model),
		Language:    strings.TrimSpace(language),
		EntityTypes: []string{"person", "organization", "concept", "tool"},
		Thresholds:  DefaultScaffoldThresholds(),
	}
}

// scaffoldReservedSegments are path components the scaffold must NEVER write
// through: the private corpus (.agents) and the .ao tree (which holds the gold
// .ao/wiki view). Enforcing this — not merely documenting it — is the bead's
// stated boundary risk (cross-family REFUTE: a reserved root or a symlinked
// layout dir could otherwise pollute the private corpus / gold wiki).
var scaffoldReservedSegments = map[string]bool{".agents": true, ".ao": true}

// hasReservedSegment reports whether any cleaned path component of p is reserved.
// Comparison is case-INSENSITIVE: on a case-insensitive volume (macOS/Windows
// default) ".AGENTS" and ".agents" are the same directory, so a case-variant
// root must be rejected too (cross-family REFUTE: ".AO/wiki" wrote into .ao).
func hasReservedSegment(p string) bool {
	for _, seg := range strings.Split(filepath.ToSlash(filepath.Clean(p)), "/") {
		if scaffoldReservedSegments[strings.ToLower(seg)] {
			return true
		}
	}
	return false
}

// pathWithin reports whether p is dir itself or nested under it (cleaned paths).
func pathWithin(p, dir string) bool {
	rel, err := filepath.Rel(dir, p)
	if err != nil {
		return false
	}
	return rel == "." || (!strings.HasPrefix(rel, ".."+string(filepath.Separator)) && rel != "..")
}

// resolveThroughSymlinks reports where a write to p WOULD actually land, without
// creating anything. It resolves the symlinks of the deepest resolvable ancestor
// and re-appends the unresolved tail. Critically it distinguishes a component
// that does not exist (walk up) from one that is a DANGLING symlink — a symlink
// whose target is missing: EvalSymlinks errors on both, but os.WriteFile/MkdirAll
// FOLLOW a dangling symlink, so its Readlink target is where the write lands
// (cross-family REFUTE: `wiki/config.yaml -> /repo/.agents/config.yaml` escaped).
func resolveThroughSymlinks(p string) string {
	p = filepath.Clean(p)
	probe := p
	var rest string
	for {
		if r, err := filepath.EvalSymlinks(probe); err == nil {
			return filepath.Clean(filepath.Join(r, rest))
		}
		// EvalSymlinks failed: is probe itself a (dangling) symlink? Lstat does
		// not follow, so it succeeds on a dangling link where EvalSymlinks fails.
		if fi, lerr := os.Lstat(probe); lerr == nil && fi.Mode()&os.ModeSymlink != 0 {
			if target, rerr := os.Readlink(probe); rerr == nil {
				if !filepath.IsAbs(target) {
					target = filepath.Join(filepath.Dir(probe), target)
				}
				return filepath.Clean(filepath.Join(target, rest))
			}
		}
		parent := filepath.Dir(probe)
		if parent == probe {
			return p
		}
		rest = filepath.Join(filepath.Base(probe), rest)
		probe = parent
	}
}

// scaffoldRealRoot validates root and returns realRoot: the fully symlink-
// resolved, absolute, cleaned root all scaffold writes are anchored to. It
// rejects — BEFORE creating anything — a root that names a reserved segment
// (.agents/.ao) or whose existing ancestor RESOLVES into the reserved tree (e.g.
// `alias -> /repo/.ao` then `init alias/wiki`). Returning the RESOLVED root (not
// the as-typed one) means every downstream write is anchored past the root's own
// symlinks (e.g. macOS /tmp -> /private/tmp), so the per-component symlink check
// in scaffoldSafeAbs only ever sees symlinks PLANTED inside the workspace.
func scaffoldRealRoot(root string) (string, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return "", fmt.Errorf("resolve scaffold root: %w", err)
	}
	absRoot = filepath.Clean(absRoot)
	if hasReservedSegment(absRoot) {
		return "", fmt.Errorf("scaffold refuses a reserved root (.agents/.ao must stay private/gold): %s", root)
	}
	// Resolve symlinks WITHOUT creating anything — catch `alias -> reserved`
	// before MkdirAll would write into it (cross-family REFUTE: write-then-reject).
	if hasReservedSegment(resolveThroughSymlinks(absRoot)) {
		return "", fmt.Errorf("scaffold root resolves into a reserved corpus path (.agents/.ao): %s", root)
	}
	if err := os.MkdirAll(absRoot, 0o750); err != nil {
		return "", fmt.Errorf("create scaffold root: %w", err)
	}
	realRoot, err := filepath.EvalSymlinks(absRoot)
	if err != nil {
		return "", fmt.Errorf("resolve scaffold root symlinks: %w", err)
	}
	if hasReservedSegment(realRoot) {
		return "", fmt.Errorf("scaffold root resolves into a reserved corpus path (.agents/.ao): %s", root)
	}
	return realRoot, nil
}

// scaffoldSafeAbs returns the write target for rel anchored at realRoot, after
// confirming it neither escapes realRoot nor names a reserved segment, AND that
// no path component between realRoot and the target is a symlink. Forbidding ANY
// symlink component (checked with Lstat, which does not follow) closes the whole
// symlink-escape class at once — dir, leaf, dangling, and multi-hop chains —
// instead of trying to predict where each symlink leads (the cross-family REFUTE
// tail: one-level Readlink missed dangling chains). A fresh scaffold has no
// symlink components, so legitimate use is unaffected.
func scaffoldSafeAbs(realRoot, rel string) (string, error) {
	abs := filepath.Clean(filepath.Join(realRoot, filepath.FromSlash(rel)))
	if !pathWithin(abs, realRoot) {
		return "", fmt.Errorf("scaffold target escapes the workspace root: %s", rel)
	}
	if hasReservedSegment(abs) {
		return "", fmt.Errorf("scaffold target names a reserved corpus path (.agents/.ao): %s", rel)
	}
	relToRoot, err := filepath.Rel(realRoot, abs)
	if err != nil {
		return "", fmt.Errorf("scaffold rel: %w", err)
	}
	cur := realRoot
	for _, seg := range strings.Split(filepath.ToSlash(relToRoot), "/") {
		if seg == "" || seg == "." {
			continue
		}
		cur = filepath.Join(cur, seg)
		if fi, lerr := os.Lstat(cur); lerr == nil && fi.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("scaffold path component %q is a symlink — refused (escape risk): %s", seg, rel)
		}
	}
	return abs, nil
}

// Scaffold creates the OpenKB-style layout + seed files + config under root.
// It is idempotent: existing directories and files are left untouched (so
// re-running never clobbers authored content), and the config is (re)written to
// reflect the requested model/language. Returns the absolute config path.
//
// It ENFORCES the raw/private vs gold/public boundary: a root that names or
// resolves into .agents/.ao, or a layout dir that symlinks into them, is
// rejected before any write.
func Scaffold(root string, cfg ScaffoldConfig) (string, error) {
	if strings.TrimSpace(root) == "" {
		return "", fmt.Errorf("scaffold: empty root")
	}
	realRoot, err := scaffoldRealRoot(root)
	if err != nil {
		return "", err
	}
	for _, dir := range ScaffoldLayout {
		abs, err := scaffoldSafeAbs(realRoot, dir)
		if err != nil {
			return "", err
		}
		if err := os.MkdirAll(abs, 0o750); err != nil {
			return "", fmt.Errorf("scaffold dir %s: %w", dir, err)
		}
	}
	for rel, content := range scaffoldSeedFiles(cfg) {
		abs, err := scaffoldSafeAbs(realRoot, rel)
		if err != nil {
			return "", err
		}
		if err := os.MkdirAll(filepath.Dir(abs), 0o750); err != nil {
			return "", fmt.Errorf("scaffold seed dir for %s: %w", rel, err)
		}
		if _, err := os.Stat(abs); err == nil {
			continue // never clobber an existing seed file
		}
		if err := os.WriteFile(abs, []byte(content), 0o600); err != nil {
			return "", fmt.Errorf("scaffold seed %s: %w", rel, err)
		}
	}
	cfgPath, err := WriteScaffoldConfig(root, cfg)
	if err != nil {
		return "", err
	}
	return cfgPath, nil
}

// WriteScaffoldConfig writes cfg as YAML to <root>/wiki/config.yaml and returns
// the absolute path.
func WriteScaffoldConfig(root string, cfg ScaffoldConfig) (string, error) {
	realRoot, err := scaffoldRealRoot(root)
	if err != nil {
		return "", err
	}
	path, err := scaffoldSafeAbs(realRoot, ScaffoldConfigRelPath)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return "", fmt.Errorf("scaffold config dir: %w", err)
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("marshal scaffold config: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return "", fmt.Errorf("write scaffold config: %w", err)
	}
	return path, nil
}

// ReadScaffoldConfig reads and parses <root>/wiki/config.yaml.
func ReadScaffoldConfig(root string) (ScaffoldConfig, error) {
	path := filepath.Join(root, filepath.FromSlash(ScaffoldConfigRelPath))
	data, err := os.ReadFile(path)
	if err != nil {
		return ScaffoldConfig{}, fmt.Errorf("read scaffold config: %w", err)
	}
	var cfg ScaffoldConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return ScaffoldConfig{}, fmt.Errorf("parse scaffold config %s: %w", path, err)
	}
	return cfg, nil
}

// SetActiveWorkspace records workspacePath as the active wiki under stateDir
// (repo-local). `ao wiki use` calls this; resolvers read ActiveWorkspace.
func SetActiveWorkspace(stateDir, workspacePath string) (string, error) {
	abs, err := filepath.Abs(workspacePath)
	if err != nil {
		return "", fmt.Errorf("resolve workspace path: %w", err)
	}
	if fi, err := os.Stat(abs); err != nil || !fi.IsDir() {
		return "", fmt.Errorf("workspace path does not exist or is not a directory: %s", abs)
	}
	statePath := filepath.Join(stateDir, filepath.FromSlash(ScaffoldStateRelPath))
	if err := os.MkdirAll(filepath.Dir(statePath), 0o750); err != nil {
		return "", fmt.Errorf("create wiki state dir: %w", err)
	}
	if err := os.WriteFile(statePath, []byte(abs+"\n"), 0o600); err != nil {
		return "", fmt.Errorf("write active workspace: %w", err)
	}
	return abs, nil
}

// ActiveWorkspace returns the workspace path recorded by SetActiveWorkspace
// under stateDir, or "" (no error) when none is set.
func ActiveWorkspace(stateDir string) (string, error) {
	statePath := filepath.Join(stateDir, filepath.FromSlash(ScaffoldStateRelPath))
	data, err := os.ReadFile(statePath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read active workspace: %w", err)
	}
	return strings.TrimSpace(string(data)), nil
}
