#!/usr/bin/env bash
#
# check-release-parity.sh — assert release-artifact parity so a built tarball,
# the in-repo tree, and any tap formula cannot silently diverge (FU5, age-8duhj).
#
# Three checks:
#   (a) README parity   — README.md inside the built tarball has the same sha256
#                         as the repo README at the release ref. Catches the
#                         v3.2.0 hazard where the tarball shipped a stale README.
#   (b) License parity  — every in-repo Homebrew formula (homebrew-tap/**/*.rb)
#                         declares `license "<L>"` matching the repo LICENSE
#                         (Apache-2.0). Catches the vestigial dir that said MIT.
#   (c) Version parity  — every in-repo formula's `version "<V>"` matches the
#                         release tag. Catches a hand-edited formula frozen at an
#                         old version (it once said 2.31.0 while the repo was 3.2.0).
#
# The canonical tap is generated by GoReleaser into boshu2/homebrew-agentops, so
# in the normal case there is NO in-repo formula and (b)/(c) simply pass — the
# gate then acts as a regression guard against anyone re-adding a stale formula.
#
# Runs in CI (post-build, in .github/workflows/release.yml) and locally.
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: scripts/check-release-parity.sh [options]

Assert parity between a built release tarball, the repo tree, and any in-repo
Homebrew formula.

Options:
  --tarball PATH        Built ao-<os>-<arch>.tar.gz to check README parity against.
                        Omit to skip check (a) and run only formula checks.
  --ref GITREF          Compare the tarball README against README.md at this git
                        ref (e.g. a tag). Default: the working-tree README.md
                        (correct in CI, where the checkout is already at the tag).
  --tag TAG             Release tag (e.g. v3.2.0). Any in-repo formula version
                        must equal it (leading 'v' ignored). Omit to skip check (c).
  --repo-root DIR       Repo root to scan. Default: git toplevel, else the
                        script's parent directory.
  --expected-license L  Override the expected SPDX license. Default: derived from
                        the repo LICENSE file (Apache-2.0).
  -h, --help            Show this help.

Exit status: 0 = all parity checks pass; 1 = a divergence was found; 2 = usage error.
USAGE
}

fail() {
    echo "check-release-parity: ERROR: $*" >&2
}

TARBALL=""
REF=""
TAG=""
REPO_ROOT=""
EXPECTED_LICENSE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --tarball)
            TARBALL="${2:-}"
            shift 2
            ;;
        --ref)
            REF="${2:-}"
            shift 2
            ;;
        --tag)
            TAG="${2:-}"
            shift 2
            ;;
        --repo-root)
            REPO_ROOT="${2:-}"
            shift 2
            ;;
        --expected-license)
            EXPECTED_LICENSE="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "unknown argument: $1"
            usage >&2
            exit 2
            ;;
    esac
done

# Resolve the repo root.
if [[ -z "$REPO_ROOT" ]]; then
    if REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        :
    else
        REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    fi
fi
if [[ ! -d "$REPO_ROOT" ]]; then
    fail "repo root does not exist: $REPO_ROOT"
    exit 2
fi

# sha256 of stdin, printed as the bare hex digest (portable across sha256sum /
# shasum -a 256).
sha256_stdin() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | awk '{print $1}'
    else
        shasum -a 256 | awk '{print $1}'
    fi
}

# Derive the expected SPDX license from the repo LICENSE file when not overridden.
if [[ -z "$EXPECTED_LICENSE" ]]; then
    license_file="$REPO_ROOT/LICENSE"
    if [[ -f "$license_file" ]]; then
        if grep -qi "Apache License" "$license_file" && grep -qi "Version 2.0" "$license_file"; then
            EXPECTED_LICENSE="Apache-2.0"
        elif grep -qi "MIT License" "$license_file"; then
            EXPECTED_LICENSE="MIT"
        else
            fail "could not derive license from $license_file; pass --expected-license"
            exit 2
        fi
    else
        fail "no LICENSE file at $license_file; pass --expected-license"
        exit 2
    fi
fi

FAILURES=0
CHECKS=0

# ── Check (a): tarball README sha256 == repo README sha256 ────────────────────
if [[ -n "$TARBALL" ]]; then
    CHECKS=$((CHECKS + 1))
    if [[ ! -f "$TARBALL" ]]; then
        fail "tarball not found: $TARBALL"
        FAILURES=$((FAILURES + 1))
    else
        # README.md sits at the archive root (wrap_in_directory: false).
        tarball_readme_sha=""
        if ! tarball_readme_sha="$(tar -xzf "$TARBALL" -O README.md 2>/dev/null | sha256_stdin)"; then
            fail "tarball $TARBALL does not contain README.md at its root"
            FAILURES=$((FAILURES + 1))
            tarball_readme_sha=""
        fi

        repo_readme_sha=""
        if [[ -n "$REF" ]]; then
            if ! repo_readme_sha="$(git -C "$REPO_ROOT" show "${REF}:README.md" 2>/dev/null | sha256_stdin)"; then
                fail "cannot read README.md at ref '$REF' in $REPO_ROOT"
                FAILURES=$((FAILURES + 1))
                repo_readme_sha=""
            fi
        else
            if [[ -f "$REPO_ROOT/README.md" ]]; then
                repo_readme_sha="$(sha256_stdin < "$REPO_ROOT/README.md")"
            else
                fail "no README.md at $REPO_ROOT/README.md"
                FAILURES=$((FAILURES + 1))
            fi
        fi

        if [[ -n "$tarball_readme_sha" && -n "$repo_readme_sha" ]]; then
            if [[ "$tarball_readme_sha" == "$repo_readme_sha" ]]; then
                echo "PASS  README parity: tarball README matches repo README (${tarball_readme_sha:0:12})"
            else
                fail "README divergence: tarball=${tarball_readme_sha:0:12} repo=${repo_readme_sha:0:12} (stale README packed in $TARBALL)"
                FAILURES=$((FAILURES + 1))
            fi
        fi
    fi
else
    echo "SKIP  README parity: no --tarball provided"
fi

# ── Checks (b)/(c): in-repo formula license + version parity ──────────────────
# Collect any Homebrew formula checked into the repo. The canonical formula is
# generated externally by GoReleaser, so finding none here is the healthy state.
formulae=()
if [[ -d "$REPO_ROOT/homebrew-tap" ]]; then
    while IFS= read -r f; do
        formulae+=("$f")
    done < <(find "$REPO_ROOT/homebrew-tap" -type f -name '*.rb' 2>/dev/null | sort)
fi

if [[ ${#formulae[@]} -eq 0 ]]; then
    echo "PASS  formula parity: no in-repo Homebrew formula (generated externally by GoReleaser)"
else
    tag_version="${TAG#v}"
    for formula in "${formulae[@]}"; do
        rel="${formula#"$REPO_ROOT"/}"

        # (b) License.
        CHECKS=$((CHECKS + 1))
        formula_license="$(grep -oE 'license[[:space:]]+"[^"]+"' "$formula" | head -1 | sed -E 's/license[[:space:]]+"([^"]+)"/\1/')"
        if [[ -z "$formula_license" ]]; then
            fail "$rel declares no license string (expected \"$EXPECTED_LICENSE\")"
            FAILURES=$((FAILURES + 1))
        elif [[ "$formula_license" != "$EXPECTED_LICENSE" ]]; then
            fail "$rel license \"$formula_license\" != repo license \"$EXPECTED_LICENSE\""
            FAILURES=$((FAILURES + 1))
        else
            echo "PASS  license parity: $rel license \"$formula_license\""
        fi

        # (c) Version — only when a release tag is supplied.
        if [[ -n "$tag_version" ]]; then
            CHECKS=$((CHECKS + 1))
            formula_version="$(grep -oE 'version[[:space:]]+"[^"]+"' "$formula" | head -1 | sed -E 's/version[[:space:]]+"([^"]+)"/\1/')"
            if [[ -z "$formula_version" ]]; then
                fail "$rel declares no version string (expected \"$tag_version\")"
                FAILURES=$((FAILURES + 1))
            elif [[ "$formula_version" != "$tag_version" ]]; then
                fail "$rel version \"$formula_version\" != release tag \"$tag_version\""
                FAILURES=$((FAILURES + 1))
            else
                echo "PASS  version parity: $rel version \"$formula_version\""
            fi
        fi
    done
fi

echo "---"
if [[ "$FAILURES" -gt 0 ]]; then
    echo "check-release-parity: FAIL ($FAILURES divergence(s) across $CHECKS check(s))" >&2
    exit 1
fi
echo "check-release-parity: OK ($CHECKS check(s) passed)"
exit 0
