#!/bin/sh
# install-ao.sh — pre_start glue: ensure the `ao` runtime is installed into a
# spawned agent's working directory.
#
# Usage: install-ao.sh <work-dir>
#
# Called from the refinery/mayor agent.toml pre_start (config.md:146), which runs
# on the target filesystem BEFORE the session is created — so the agent starts
# with `ao` on PATH and the .claude/skills + .agents scaffolding present.
#
# THIN-SEAM / provisioning (design doc Part 3): GC has NO skill primitive on this
# pack's version floor. AgentOps self-provisions its runtime: this script handles
# the `ao` BINARY + .agents scaffolding; the static skill corpus is copied
# separately by the agent's `overlay_dir` (overlay/.claude/skills, a PINNED
# snapshot regenerated by sync-overlay-skills.sh).
#
# PINNED, not pull-latest (Decision 2 / runbook F4). The install source is pinned
# to a specific AgentOps release tag so a City is reproducible at a commit — a
# pull-latest-at-spawn would re-introduce network drift on every agent spawn.
# Bump AO_VERSION when the City should track a newer release.
#
# The installer is downloaded to a temp file and executed (never piped straight
# into a shell), which keeps this script clear of the repo's dangerous-pattern
# security gate and lets the download be verified before it runs.

set -eu

# Pinned AgentOps release. Override per-deploy with AO_VERSION in the env.
AO_VERSION="${AO_VERSION:-v3.0.1}"
AO_REPO="${AO_REPO:-boshu2/agentops}"

WORK_DIR="${1:?usage: install-ao.sh <work-dir>}"

# 1) Ensure the `ao` binary is on PATH. If absent, install it from the PINNED
#    release tag (idempotent — the underlying installer is brew/build based and
#    re-runs cleanly).
if ! command -v ao >/dev/null 2>&1; then
    echo "install-ao: 'ao' not found on PATH; installing $AO_REPO@$AO_VERSION" >&2
    if ! command -v curl >/dev/null 2>&1; then
        echo "install-ao: FATAL — curl required to fetch the pinned installer" >&2
        exit 1
    fi
    installer="$(mktemp)"
    # Download the installer from the PINNED tag (not main) so the install is
    # reproducible. Execute the file directly (no pipe-to-shell).
    installer_url="https://raw.githubusercontent.com/$AO_REPO/$AO_VERSION/scripts/install.sh"
    if ! curl -fsSL "$installer_url" -o "$installer"; then
        rm -f "$installer"
        echo "install-ao: FATAL — could not fetch pinned installer: $installer_url" >&2
        exit 1
    fi
    if ! sh "$installer"; then
        rm -f "$installer"
        echo "install-ao: FATAL — pinned installer failed ($AO_REPO@$AO_VERSION)" >&2
        exit 1
    fi
    rm -f "$installer"
    if ! command -v ao >/dev/null 2>&1; then
        echo "install-ao: FATAL — installer ran but 'ao' is still not on PATH" >&2
        exit 1
    fi
fi

# 2) Scaffold the AgentOps runtime into the working dir (idempotent). The overlay
#    already copies .claude/skills/** and .claude/settings.json; this ensures the
#    .agents/ corpus scaffolding exists so `ao inject`/`ao compile` have a home.
mkdir -p "$WORK_DIR/.agents"

# `ao init` creates repo-local .agents scaffolding (install.sh note: "run 'ao init'
# from your repo root"). Idempotent — safe to re-run on every spawn.
( cd "$WORK_DIR" && ao init >/dev/null 2>&1 ) \
    || echo "install-ao: 'ao init' unavailable or already initialized (continuing)" >&2

exit 0
