#!/usr/bin/env bash
# sync-overlay-skills.sh — regenerate the pinned skills overlay snapshot.
#
# The reference Gas City pack ships a PINNED, self-contained copy of a CURATED
# core-loop subset of the repo's skills/ into
#   packs/agentops/overlay/.claude/skills/
# GC's `overlay_dir` recursively copies that directory into every spawned agent's
# working dir at startup, so the agent can run the loop skills offline (GC has no
# skill primitive of its own on the version floor this pack targets).
#
# Source of truth stays skills/ in the repo root. This snapshot is DERIVED —
# exactly like the installed ~/.claude/skills/ copies. Re-run this script whenever
# a curated skill changes; the city-skills-snapshot drift gate (CI) fails if the
# committed snapshot drifts from skills/.
#
# CURATED, not full: the City ships the loop runtime an agent needs (rpi +
# research/plan/implement/crank/validate, evolve, inject, goals, standards,
# domain, the shared dependency, plus the mayor-loop skills the prompts invoke),
# NOT all ~80 skills. Rationale + the full-vs-curated tradeoff are in
# packs/agentops/FINALIZE-NOTES.md. Edit CURATED_SKILLS below to change the set.
#
# COPY, never symlink — the repo plugin-load-test rejects every symlink. This
# script asserts the snapshot is symlink-free before it succeeds.
#
# Usage:
#   packs/agentops/assets/scripts/sync-overlay-skills.sh            # regenerate
#   packs/agentops/assets/scripts/sync-overlay-skills.sh --check    # drift check (no writes)
set -euo pipefail

# Curated core-loop skill set. Keep alphabetized within logical groups.
CURATED_SKILLS=(
  # rpi inner loop (research -> plan -> implement -> validate) + variants
  rpi research plan implement crank validate validation
  # outer loop the mayor/orchestrator drives
  evolve post-mortem pr-validate council harvest
  # corpus / context compounding
  inject compile curate
  # strategic + standards + vocabulary
  goals standards domain
  # supporting loop skills the prompts invoke
  discovery scope handoff recover status provenance
  # shared dependency referenced by the loop skills above
  shared
)

# Resolve repo root from this script's location: assets/scripts -> pack -> packs -> repo.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SRC_DIR="$REPO_ROOT/skills"
DEST_DIR="$REPO_ROOT/packs/agentops/overlay/.claude/skills"
PROVENANCE="$DEST_DIR/PROVENANCE.md"

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

if [ ! -d "$SRC_DIR" ]; then
  echo "FATAL: skills source dir not found: $SRC_DIR" >&2
  exit 2
fi

# Build the snapshot into a temp dir first (so --check never mutates the tree).
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

build_snapshot() {
  local out="$1"
  mkdir -p "$out"
  local s
  for s in "${CURATED_SKILLS[@]}"; do
    if [ ! -d "$SRC_DIR/$s" ]; then
      echo "FATAL: curated skill '$s' not found in $SRC_DIR" >&2
      exit 2
    fi
    # cp -R of plain files; --no-dereference would error if any symlink existed,
    # so we copy then assert symlink-free below.
    cp -R "$SRC_DIR/$s" "$out/$s"
  done
  # Provenance note (kept inside the snapshot so the source is self-documenting).
  cat > "$out/PROVENANCE.md" <<'EOF'
# AgentOps skills overlay — PINNED, DERIVED snapshot

> Generated by `packs/agentops/assets/scripts/sync-overlay-skills.sh`. Do NOT
> hand-edit the skills here — edit the source under the repo-root `skills/` and
> re-run the sync script.

## What this is

A PINNED copy of a CURATED core-loop subset of the repo's `skills/`. GC's
`overlay_dir` recursively copies this tree into every spawned agent's working dir
at startup, so the agent can run the loop skills without network access.

- **Source of truth:** `skills/` in the repo root. This is a derived snapshot.
- **Curated, not full:** ships the loop runtime an agent needs (rpi + its inner
  research/plan/implement/crank/validate phases, evolve, inject/compile/curate,
  goals, standards, domain, and the mayor-loop skills the prompts invoke), NOT
  all ~80 skills. See `packs/agentops/FINALIZE-NOTES.md` for the full-vs-curated
  tradeoff and how to widen the set.
- **Refresh:** `packs/agentops/assets/scripts/sync-overlay-skills.sh`.
- **No symlinks:** the snapshot is plain files only — the repo plugin-load-test
  rejects symlinks, and the sync script asserts symlink-free before committing.
EOF
}

assert_no_symlinks() {
  local dir="$1"
  local found
  found="$(find "$dir" -type l -print 2>/dev/null || true)"
  if [ -n "$found" ]; then
    echo "FATAL: symlinks found in snapshot (plugin-load-test would reject):" >&2
    echo "$found" >&2
    exit 1
  fi
}

build_snapshot "$TMP_DIR"
assert_no_symlinks "$TMP_DIR"

if [ "$CHECK_ONLY" = "1" ]; then
  if [ ! -d "$DEST_DIR" ]; then
    echo "DRIFT: snapshot dir does not exist: $DEST_DIR" >&2
    exit 1
  fi
  if diff -r -q "$TMP_DIR" "$DEST_DIR" >/dev/null 2>&1; then
    echo "OK: overlay skills snapshot is in sync with skills/ (curated set)."
    exit 0
  fi
  echo "DRIFT: overlay skills snapshot differs from skills/. Run:" >&2
  echo "  packs/agentops/assets/scripts/sync-overlay-skills.sh" >&2
  diff -r -q "$TMP_DIR" "$DEST_DIR" >&2 || true
  exit 1
fi

# Regenerate: replace the snapshot dir wholesale.
rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
cp -R "$TMP_DIR/." "$DEST_DIR/"
assert_no_symlinks "$DEST_DIR"

count="$(find "$DEST_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
echo "OK: synced $count curated skills into $DEST_DIR (symlink-free)."
echo "    Provenance: $PROVENANCE"
